### ISSUE TITLE
Question: applying to old issues

### ISSUE THREAD

**Issue by rstacruz** [noqcks/pull-request-size#15]
First of all, thank you for Pull Request Size! It helps me keep a huge PR backlog organised.

Is there any way I can update old pull requests that were present before I installed the app?

I've found that I can individually edit a pull request's description to force-retrigger an update... but I was wondering if it was possible to do so en masse across all open issues somehow.

**Comment by noqcks** [comment]
Hmmmm unfortunately not. 

Yes you can update each of the pull requests manually to trigger a request, but not sure of any way to force an update across the board. You could make a script on your end to traverse all your PRs and make a small update perhaps.

The reason for this os because pull-request-size listens to GitHub webhook activity. And if there is no update, then no event is sent to pull-request-size. 

And I don't believe I have the ability to traverse through all your PRs. I've attempted to setup permission so the the surface area is as small as possible.
