### ISSUE TITLE
The bot does not seems to work when a generated file is committed

### ISSUE THREAD

**Issue by courentin** [noqcks/pull-request-size#35]
I'm not sure it's the expected behaviour but as soon there is a generated file in a PR (marked as `linguist-generated=true` in `.gitattributes`) the bot does not add/update a label.

When I remove the file from the PR, it adds/updates the label again.

**Comment by noqcks** [comment]
I can't seem to reproduce this behaviour. I created [this PR](https://github.com/noqcks/pull-request-size/pull/45) to test and a label was added successfully. Let me know if you can still reproduce.

My gut feeling is that this issue was fixed when we fixed a package in the generated package: https://github.com/noqcks/generated/commit/a5e25fa637c7214ca8a5f2832dc49391d2e5e4d7

**Comment by courentin** [comment]
It seems to work indeed! Thank you 🙏
